### ISSUE TITLE
Can't get RooCode to recognize supportsComputerUse with LiteLLM provider

### ISSUE THREAD

**Issue by ndraiman** [RooCodeInc/Roo-Code#3572]
### App Version

3.16.6

### API Provider

LiteLLM

### Model Used

Claude 3.7 Sonnet

### 🔁 Steps to Reproduce

1. Choose LiteLLM provider and enter details
2. Choose Claude 3.7 Sonnet
3. Computer use support is not recognized.

![Image](https://github.com/user-attachments/assets/a0294add-9643-42b0-a3d5-38d0f682caec)

### 💥 Outcome Summary (Optional)

I can't seem to get RooCode to recognize Claude 3.7 Sonnet as supports computer use via LiteLLM.

Tried several model names to try and match COMPUTER_USE_MODELS , but it doesn't work for me

example configurations i tried:

```
- model_name: anthropic/claude-3-7-sonnet-20250219
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic/claude-3.7-sonnet
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
```

Seems to be working fine if choosing **Anthropic** provider and specifying the **LiteLLM** proxy as the base url.
But need to have model_name as `claude-3-7-sonnet-20250219 `

### 📄 Relevant Logs or Errors

```shell

```
