### ISSUE TITLE
YAML groups list parsing broken

### ISSUE THREAD

**Issue by VelocityRa** [RooCodeInc/Roo-Code#3991]
### App Version

v3.18.4

### API Provider

Not Applicable / Other

### Model Used

N/A

### 🔁 Steps to Reproduce

Make a custom roo mode with two or more groups, eg:

```yaml
    groups:
      - - edit
        - fileRegex: \.md$
          description: Markdown documentation files
      - - edit
        - fileRegex: \.ya?ml$
          description: YAML configuration files for documentation
```

With either one of them it works:
```yaml
    groups:
      - - edit
        - fileRegex: \.md$
          description: Markdown documentation files
```

### 💥 Outcome Summary

Custom Mode doesn't show up in combobox.

### 📄 Relevant Logs or Errors (Optional)

```shell

```

**Comment by hannesrudolph** [comment]
I am not sure I understand the problem here. 

I'm closing this issue temporarily as `can't reproduce`, but to be clear, this does not mean your information was insufficient or unclear about the existence of the problem. Rather, to effectively pass this to the right team member, we require explicitly numbered steps that anyone on our team can precisely follow:

- To **initially confirm** the issue.
- To **implement a fix**.
- To **verify the fix** by following the exact same steps again.

**To reopen, please provide explicitly:**
- Clearly numbered, step-by-step instructions.
- Exact error messages or precise unexpected behaviors.
- Specific environment details (OS, IDE, software versions).

**Please avoid:**
- General descriptions without reproducible instructions ("it's broken", "doesn't work as expected").
- Screenshots or errors without context and explicit steps.

Once clear reproduction steps are provided, I'll promptly reopen the issue and move it forward internally.

**Comment by VelocityRa** [comment]
Run:
```
mkdir roo-test
code roo-test
```

Make a new file in that dir called `.roomodes` with these contents - the important part is that there are more than one filename regexes:
```yaml
customModes:
  - slug: documentation
    name: "📝 Documentation"
    roleDefinition: |
      Doesn't matter.
    whenToUse: |
      Doesn't matter.
    customInstructions: |
      Doesn't matter.
    groups:
      - read
      - command
      - - edit
        - fileRegex: \.(md|markdown)$
          description: Markdown files
        - fileRegex: \.pages$
          description: MkDocs navigation files
    source: project
```

**Issue: "Documentation" is not on the mode list in Roo's combobox.**

![Image](https://github.com/user-attachments/assets/20cfd1a7-4d9f-4af9-919f-953a377ff6a9)

Restarting VSCode does not fix it either.

Change edit group to just one filename regex
```yaml
      - - edit
        - fileRegex: \.(md|markdown)$
          description: Markdown files
```

"Documentation" immediately appears on the mode list.

![Image](https://github.com/user-attachments/assets/cb08779b-3109-41f5-bbd7-8a3f07b65a58)

This also proves that the multi-folder workspace behavior (bug?) is unrelated, since I can repro it in this simple single-folder workspace.

---

Roo Code version: v3.19.6 (latest)
VS Code version: 1.100.3 (latest)
OS: Ubuntu 24.04
