### ISSUE TITLE
RooCode codesearch feature does not work with LM Studio

### ISSUE THREAD

**Issue by christopherowen** [RooCodeInc/Roo-Code#4435]
### App Version

 3.19.4

### API Provider

LM Studio

### Model Used

nomic-embed-code

### 🔁 Steps to Reproduce

On MacOS Sequoia 15.5, using LM Studio 0.3.16.

LM Studio will produce errors during this Indexing Process of:

```
Unexpected endpoint or method. (POST /embeddings). Returning 200 anyway
```

testing the API with python returns a result and no error in the LM Studio console:

```
# Make sure to `pip install openai` first
from openai import OpenAI
client = OpenAI(base_url="http://localhost:1234/v1", api_key="lm-studio")

def get_embedding(text, model="nomic-embed-code"):
   return client.embeddings.create(input = [text], model=model).data[0].embedding

print(get_embedding("Once upon a time, there was a cat."))
```

Also, testing with curl produces a result and no error in the LM Studio console:
```
curl http://127.0.0.1:1234/v1/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "model": "text-embedding-nomic-embed-code",
    "input": "Some text to embed"
  }'
```

Steps to reproduce:
- Download nomic-embed-code to LM Studio: https://huggingface.co/lmstudio-community/nomic-embed-code-GGUF
- Edit the model settings and set 'Override Domain Type' to 'Text Embedding'

- Launch Qdrant docker using the following `docker-compose.yaml`:
```
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
```

- Visit RooCode Experimental features
- Set Enable Codebase Indexing
 - Embeddings Provider: OpenAI Compatible
 - Base URL: http://localhost:1234 <- default LM Studio
 - API Key: fakekey
 - Model: nomic-embed-code
 - Embedding Dimension: tried both blank and 3584

 - Qdrant URL: http://localhost:6333
 - Qdrant Key: provided during Qdrant first launch

 - click Save
 - click Start Indexing

Some debugging that was attempted:
- As I do not know what Dimensions are, I tried setting it to the qwen2.embedding_length of 3584.
- I tried setting the context window of the model to 3584.

### 💥 Outcome Summary

I expected the indexing operation to produce an index of my codebase.  Instead there were errors during the indexing process in LM Studio and an empty index was produced in Qdrant with 0 Points, 8 Segments, and 1 Shard.

### 📄 Relevant Logs or Errors (Optional)

```shell

```
