### ISSUE TITLE
Codebase indexing qdrant docker compose can not start indexing

### ISSUE THREAD

**Issue by FabianHertwig** [RooCodeInc/Roo-Code#4441]
### App Version

3.19.5

### API Provider

OpenAI

### Model Used

N/A

### 🔁 Steps to Reproduce

Setup codebase indexing with a docker compose file like described here: https://docs.roocode.com/features/experimental/codebase-indexing

```yaml
version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
volumes:
  qdrant_storage:
```

Go to codebase indexing settings and configure and save them. 

### 💥 Outcome Summary

I expected I could start indexing, but the start indexing button is grayed out. There is a hint to save the settings to start indexing.

### 📄 Relevant Logs or Errors (Optional)

```shell
In the Roocode output there is this line


[CodeIndexManager] Error during background CodeIndexManager configuration/indexing: Cannot create services: Code indexing is not properly configured
```

**Comment by FabianHertwig** [comment]
So I have restarted Cursor and the start indexing button was no longer grayed out. But when clicking it nothing happened and there was no output in the Roocode output. 
I then ran the `Developer: Reload Window` command and then the indexing started and I saw the progress bar.

Seems to me like there might be an issue with the UI updating correctly.

**Comment by FabianHertwig** [comment]
Also I would recommend adding the `QDRANT__SERVICE__API_KEY` to the env section of the docker file, otherwise it is really confusing on what to put in the `Qdrant` key section in the settings. I think there even was some default value.

```yaml
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
    environment:
      QDRANT__SERVICE__API_KEY: mysecretpassword
    volumes:
      - qdrant_storage:/qdrant/storage
```
