### ISSUE TITLE
Roo Code ignores mode permissions if concurrent file edits are enabled

### ISSUE THREAD

**Issue by dsent** [RooCodeInc/Roo-Code#4732]
### App Version

3.20.3

### API Provider

VS Code Language Model API

### Model Used

Claude 4

### 🔁 Steps to Reproduce

I've worked on something with Architect, and at some point, it just started editing PowerShell scripts despite not having permission to do so.

### 💥 Outcome Summary

I have a modified version of Architect on the project level, but its edition scope is limited:
```yaml
    groups:
      - read
      - - edit
        - fileRegex: \.(md|yaml|json|toml|.+ignore|roomodes)$
          description: Documentation and configs
      - browser
      - command
      - mcp
```
The relevant task screenshot:
![Image](https://github.com/user-attachments/assets/51595d0f-ab95-4ee5-8668-881683a65f3c)

### 📄 Relevant Logs or Errors (Optional)

```shell

```
